### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by joyuhou** [eddiesigner/liebling#185]
Hi! I'm using your theme for our blog, this is a great theme! 
I'm very new to Ghost and new to GitHub/coding as well. I didn't have any trouble uploading the theme, but I was wondering if there is any way that we can 1) make the light-mode as default 2) customize font? 

Currently, the theme default is dark mode, could you help me navigate these questions? (Apology if they sound like super beginner question.) 

Thanks!

**Comment by eddiesigner** [comment]
Hi!

The default theme is light, if you see it dark is because your operating system has dark mode enabled.

Currently the dark theme is shown when devices that support `@media (prefers-color-scheme: dark)` have the dark mode enabled. If the device doesn't support that or if you have the dark mode turned off in your device then the light theme is shown.

More info about this here: https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme

If you want to use a different font from Google Fonts you can change the [line 48](https://github.com/eddiesigner/liebling/blob/master/default.hbs#L48) in the file `default.hbs` to include the font family you want.

Then head over your Ghost admin and click on **Code injection**. There you have to inject the following style into the **Site Header** section:

```html
<style>
body {
  /* Replace Source Sans Pro with the font family you included before */
  font-family: 'Source Sans Pro', Helvetica, Arial, sans-serif;
}
</style>
```

Hope it helps.

**Comment by joyuhou** [comment]
Thanks for the dark mode explanation.  These really help. I will definitely look into this.

**Comment by eddiesigner** [comment]
I will close this for now, please feel free to reopen it if needed.

**Comment by swalahamani** [comment]
Hi @eddiesigner,

Any way to disable this auto-switching to dark-mode (along with keeping the explicit switch option for the user)?

**Comment by eddiesigner** [comment]
@swalahamani Hi, 

It is possible but you would need to create a development environment to make deeper changes like this one in the theme, you can follow this guide to learn how to do that: https://github.com/eddiesigner/liebling/wiki/Theme-development-with-Docker

Once everything is ready you can replace the content of the file `src/sass/common/_themes.scss` with this code:

```scss
[data-theme="light"] {
  --background-color: #fff;
  --primary-foreground-color: #4a4a4a;
  --secondary-foreground-color: #000;
  --primary-subtle-color: #0470ee;
  --secondary-subtle-color: #f4f8fd;
  --titles-color: #333;
  --link-color: #133467;
  --primary-border-color: #9b9b9b;
  --secondary-border-color: aliceblue;
  --article-shadow-normal: 0 10px 10px rgba(0,0,0,0.08);
  --article-shadow-hover: 0 4px 60px 0 rgba(0,0,0,0.2);
  --transparent-background-color: rgba(255,255,255,0.99);
  --footer-background-color: #133467;
  --submenu-shadow-color-opacity: 0.25;
  --button-shadow-color-normal: rgba(108, 108, 108, 0.2);
  --button-shadow-color-hover: rgba(108, 108, 108, 0.3);
  --table-background-color-odd: #fafafa;
  --table-head-border-bottom: #e2e2e2;
  --toggle-darkmode-button-display-moon: block;
  --toggle-darkmode-button-display-sun: none;
  --toggle-darkmode-background-color: rgba(0, 0, 0, 0.05);
  --header-menu-gradient-first-color: rgba(255, 255, 255, 0);
  --header-menu-gradient-second-color: rgba(255, 255, 255, 1);
}

[data-theme="dark"] {
  --background-color: #111;
  --primary-foreground-color: #ccc;
  --secondary-foreground-color: #fff;
  --primary-subtle-color: #2c2fe6;
  --secondary-subtle-color: #141920;
  --titles-color: #b4b4b4;
  --link-color: #b6b7f6;
  --primary-border-color: #1d1d1d;
  --secondary-border-color: #0f0f0f;
  --article-shadow-normal: 0 4px 5px 5px rgba(0,0,0,0.1);
  --article-shadow-hover: 0 4px 5px 10px rgba(0,0,0,0.1);
  --transparent-background-color: rgba(0,0,0,0.99);
  --footer-background-color: #080808;
  --submenu-shadow-color-opacity: 0.55;
  --button-shadow-color-normal: rgba(10, 10, 10, 0.5);
  --button-shadow-color-hover: rgba(10, 10, 10, 0.5);
  --table-background-color-odd: #050505;
  --table-head-border-bottom: #1d1d1d;
  --toggle-darkmode-button-display-moon: none;
  --toggle-darkmode-button-display-sun: block;
  --toggle-darkmode-background-color: rgba(0, 0, 0, 0.5);
  --header-menu-gradient-first-color: rgba(17, 17, 17, 0);
  --header-menu-gradient-second-color: rgba(17, 17, 17, 0.65);
}
```
