### ISSUE TITLE
Using custom fonts - new instructions

### ISSUE THREAD

**Issue by aidenmitchell** [eddiesigner/liebling#250]
I saw this issue: https://github.com/eddiesigner/liebling/issues/84, however, it seems the instructions provided there are outdated. Are there updated instructions? Thanks!

**Comment by eddiesigner** [comment]
If you want to use a different font you have to create a folder within `/assets/fonts` and put your font files there.

Then you have to open the file `default.hbs` and replace the following code with your own font-face code:

```css
/* source-sans-pro-regular */
      @font-face {
        font-family: 'Source Sans Pro';
        font-style: normal;
        font-weight: 400;
        font-display: swap;
        src: local('Source Sans Pro Regular'), local('SourceSansPro-Regular'),
            url("{{asset 'fonts/source-sans-pro/source-sans-pro-regular.woff2'}}") format('woff2'),
            url("{{asset 'fonts/source-sans-pro/source-sans-pro-regular.woff'}}") format('woff');
      }

      /* source-sans-pro-600 */
      @font-face {
        font-family: 'Source Sans Pro';
        font-style: normal;
        font-weight: 600;
        font-display: swap;
        src: local('Source Sans Pro SemiBold'), local('SourceSansPro-SemiBold'),
            url("{{asset 'fonts/source-sans-pro/source-sans-pro-600.woff2'}}") format('woff2'),
            url("{{asset 'fonts/source-sans-pro/source-sans-pro-600.woff'}}") format('woff');
      }

      /* source-sans-pro-700 */
      @font-face {
        font-family: 'Source Sans Pro';
        font-style: normal;
        font-weight: 700;
        font-display: swap;
        src: local('Source Sans Pro Bold'), local('SourceSansPro-Bold'),
            url("{{asset 'fonts/source-sans-pro/source-sans-pro-700.woff2'}}") format('woff2'),
            url("{{asset 'fonts/source-sans-pro/source-sans-pro-700.woff'}}") format('woff');
      }
```

Be aware of using the `{{asset}}` helper and of using your new folder name.

Finally inject the following style in the Admin panel (Code Injection -> Site Header section):

```html
<style>
body {
  font-family: 'YOUR NEW FONT NAME GOES HERE', Helvetica, Arial, sans-serif;
}
</style>
```

I strongly recommend to not change the font since it's an important part of the theme and probably you will need to change multiple styles in some places to make it perfect, if that's the case then you have to fix it by yourself.
