### ISSUE TITLE
Hide the hero picture, on the homepage only with the code injection page

### ISSUE THREAD

**Issue by MrNovy** [eddiesigner/liebling#361]
Hi, is it possible to hide the hero picture, tittle and description on the homepage only with the code injection page which is included in Ghost??
Best regards!

**Comment by ClassUnwind** [comment]
If I understand correctly, then something like this might do the trick:
```css
<style>
body[class~="home-template"] > main > section.m-hero { display: none; }
</style>
```

That will hide the header section completely, and only on the home page.
