### ISSUE TITLE
CSS problems with several input types

### ISSUE THREAD

**Issue by Nemental** [eddiesigner/liebling#501]
I created a page and inserted custom HTML for a form, but the rendered result is unusable. You can see an example in the screenshots below.

With the following CSS snippet I was able to fix the width and padding a bit, but `appearance` doesn't work because it's not overridable.
```css
input[type='radio'], input[type='checkbox'], label>input
{
    width: auto !important;
    padding: 0px !important;
    appearance: auto !important;
    -webkit-appearance: auto !important;
}
```
<details>
<summary>Screenshots</summary>

![Bildschirmfoto 2023-01-12 um 16 43 04](https://user-images.githubusercontent.com/15136847/212113132-73b19e5c-e21e-46aa-9ea3-51bfc27f3b69.png)

![Bildschirmfoto 2023-01-12 um 16 43 25](https://user-images.githubusercontent.com/15136847/212113140-c23e98b1-1f35-47ff-872b-11641a9873c0.png)

</details>
