### ISSUE TITLE
Force dark mode

### ISSUE THREAD

**Issue by hvrry** [eddiesigner/liebling#62]
Hey,

First of all love the theme and especially dark mode!

Is it possible to force dark mode for all users regardless of operating system theme?

Cheers

**Comment by eddiesigner** [comment]
There is no way to force dark mode, BUT, you can build your own theme version **with only dark mode enabled**.

To do that just follow these steps:

1. Install [Nodejs](https://nodejs.org/en/download/) and [npm](https://www.npmjs.com/get-npm).

2. Clone this repository.

3. Open `src/sass/common/_themes.scss` with a code editor.

4. Replace all the content of that file with this code:

```scss
:root {
  --background-color: #111;
  --primary-foreground-color: #ccc;
  --secondary-foreground-color: #fff;
  --primary-subtle-color: #2c2fe6;
  --secondary-subtle-color: #141920;
  --titles-color: #b4b4b4;
  --link-color: #2c2fe6;
  --primary-border-color: #1d1d1d;
  --secondary-border-color: #0f0f0f;
  --article-shadow-normal: 0 4px 5px 5px rgba(0,0,0,0.1);
  --article-shadow-hover: 0 4px 5px 10px rgba(0,0,0,0.1);
  --transparent-background-color: rgba(0,0,0,0.99);
  --foter-background-color: #080808;
  --submenu-shadow-color-opacity: 0.55;
  --button-shadow-color-normal: rgba(10, 10, 10, 0.5);
  --button-shadow-color-hover: rgba(10, 10, 10, 0.5);
}
```

5. Save it.

6. Open a terminal and go to the `src` directory.

7. Run `npm install`.

8. Run `npm run production`.

This last command will generate the file `liebling.zip` in the root of the theme directory. Then you can upload that file to your own Ghost instance ;)
